version: "3.9"
services:
    script:
        build: .
        networks:
            - app-network
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: "wildberries"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "991155"
        volumes:
            - ./psqsql/data:/var/lib/postgresql
            - ./psqsql/Setup.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
        
